version: '3.7'

services:
  backend:
    image: lcdamy/backend-alight-challenge:1.0
    platform: linux/x86_64
    ports:
      - "3003:3001"
    depends_on:
      - postgres
    environment:
      - HOST=localhost
      - PORT=3003
      - TOKEN_SECRET=408048284902KNJKJ0423-4023NKKNN-NFJNIO0230J000-ISHDU0
      - FRONTEND_URL=http://localhost:3002
      - BASE_URL=http://localhost:3003/
      - API_URL=http://localhost:3003/api/v1
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=avnadmin
      - DB_PASSWORD=AVNS_4fG2dirdBzNwc6QEnhU
      - DB_NAME=defaultdb
      - GMAIL_EMAIL=zudanga@gmail.com
      - GMAIL_PASSWORD=spbb bnsw ziol htbz
      - LOGO_URL=https://rci-files.lon1.digitaloceanspaces.com/rci-files/1750462403519-Group%202635.png
      - DB_SSL=false
    networks:
      - alight_network

  postgres:
    image: postgres:latest
    platform: linux/x86_64
    ports:
      - "10901:5432"
    environment:
      - POSTGRES_DB=defaultdb
      - POSTGRES_USER=avnadmin
      - POSTGRES_PASSWORD=AVNS_4fG2dirdBzNwc6QEnhU
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - alight_network

  frontend:
    image: lcdamy/frontend-alight-challenge:1.0
    platform: linux/x86_64
    ports:
      - "3002:3000"
    depends_on:
      - backend
    environment:
      - GOOGLE_CLIENT_ID=120025142035-9rjd81fca71ffp9h6ug78fpp2spt6nk6.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - NEXTAUTH_SECRET=DSFSDGFGTRETTRBGFGFDSFDSFDSFDSF
      - NEXTAUTH_URL=http://localhost:3002
      - NEXT_PUBLIC_API_URL=http://localhost:3003
      - NEXT_PUBLIC_FRONTEND_URL=http://localhost:3002

    networks:
      - alight_network

volumes:
  postgres_data:

networks:
  alight_network: