version: '3.7'

services:
  backend:
    image: lcdamy/backend-alight-challenge:1.0
    platform: linux/x86_64
    ports:
      - "3003:3001"
    depends_on:
      - postgres
    environment:
      - HOST=${HOST}
      - PORT=${ports}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - GMAIL_EMAIL=${GMAIL_EMAIL}
      - GMAIL_PASSWORD=${GMAIL_PASSWORD}
      - LOGO_URL=${LOGO_URL}
      - DB_SSL=${DB_SSL}
    networks:
      - alight_network
    restart: unless-stopped

  postgres:
    image: postgres:latest
    platform: linux/x86_64
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - alight_network
    restart: unless-stopped

  frontend:
    image: lcdamy/frontend-alight-challenge:1.0
    platform: linux/x86_64
    ports:
      - "3002:3000"
    depends_on:
      - backend
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    networks:
      - alight_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  alight_network:
