version: '3.7'

services:
  backend:
    image: lcdamy/backend-alight-challenge:1.0
    platform: linux/x86_64
    ports:
      - "3001:3003"
    depends_on:
      - postgres
    environment:
      - HOST=localhost
      - PORT=3003
      - TOKEN_SECRET=408048284902KNJKJ0423-4023NKKNN-NFJNIO0230J000-ISHDU0
      - FRONTEND_URL=http://localhost:3002
      - BASE_URL=http://localhost:3003/
      - API_URL=http://localhost:3003/api/v1
      - DB_HOST=pg-1843c0a3-backend-alight-challenge.g.aivencloud.com
      - DB_PORT=10901
      - DB_USERNAME=avnadmin
      - DB_PASSWORD=AVNS_4fG2dirdBzNwc6QEnhU
      - DB_NAME=defaultdb
      - GMAIL_EMAIL=zudanga@gmail.com
      - GMAIL_PASSWORD=spbb bnsw ziol htbz
      - LOGO_URL=https://rci-files.lon1.digitaloceanspaces.com/rci-files/1750462403519-Group%202635.png
    networks:
      - alight_network

  postgres:
    image: postgres:latest
    platform: linux/x86_64
    ports:
      - "8043:5432"
    environment:
      - POSTGRES_DB=defaultdb
      - POSTGRES_USER=avnadmin
      - POSTGRES_PASSWORD=AVNS_4fG2dirdBzNwc6QEnhU
    volumes:
      - postgres_data:"/var/lib/postgresql/data"
    networks:
      - alight_network

  frontend:
    image: lcdamy/frontend-alight-challenge:1.0
    platform: linux/x86_64
    ports:
      - "3000:3002"
    depends_on:
      - backend
    environment:
      - GOOGLE_CLIENT_ID=120025142035-boltjjackct3861jnaikoeilpbbbfaua.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GITHUB_CLIENT_ID=Ov23liAotIvfUnVtlLh9
      - GITHUB_CLIENT_SECRET=d2a8b0e315bdbf49b5a87fbc7532f506fa51d058
      - NEXTAUTH_SECRET=secret
      - NEXTAUTH_URL=http://localhost:3002
      - NEXT_PUBLIC_API_URL=http://localhost:3003
      - NEXT_PUBLIC_FRONTEND_URL=http://localhost:3002
      - NEXT_PUBLIC_DEFAULT_PASSWORD=123456789
    networks:
      - alight_network

volumes:
  postgres_data:

networks:
  alight_network: